name: Python application test with Github Actions

on: [push] #every time I push the code

jobs:
  build:

    runs-on: ubuntu-latest #run everything on a container ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5 #runs python3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: | # and then run all
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
